### ISSUE TITLE
Uncaught (in promise) DOMException

### ISSUE THREAD

**Issue by maheshambiga** [benwiley4000/cassette#126] opened 2017-10-24 15:10 UTC
Getting the below error when I leave an audio to play, click browser back button and then re-enter to play another audio. 

`Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().`

**Added by @benwiley4000: This also seems to happen when waking a machine from suspend, as originally reported in #55.**

**Comment by benwiley4000** [comment] 2017-10-24 15:17
Hm - this is the same error message as #28 (which I marked as `wontfix`). However I haven't noticed this scenario before.

To confirm the repro steps:
1. Play an audio file in the player
2. Hit back
3. Hit forward
4. Hit play again

Did I miss or misinterpret anything?

**Comment by maheshambiga** [comment] 2017-10-25 06:29
@benwiley4000 You got it right. After theses steps, the audio does not work at all.

**Comment by benwiley4000** [comment] 2017-11-09 08:41
@maheshambiga thanks for answering, and I'm sorry for not responding quickly. This is on my radar - however I've been a bit overloaded with other projects. I may have a little bit of time during the coming weekend to take a look! Feel free to ping me on [twitter](https://twitter.com/benwiley4000) to remind me, if you want.

**Comment by benwiley4000** [comment] 2017-12-05 05:04
@maheshambiga I just got around to testing this - sorry for the delay. I've tried it in Chrome, Safari, and Firefox, and following the previously enumerated steps accessing [this page](https://benwiley4000.github.io/react-responsive-audio-player/), I'm unable to reproduce the issue. In fact, the audio playback resumes immediately in each browser.

What browser and version number are you using? Could you maybe provide a more detailed set of steps, and maybe even a screencast if possible? If not, detailed steps will do.

**Comment by benwiley4000** [comment] 2018-03-25 01:51
@maheshambiga are you able to follow up on this?

**Comment by benwiley4000** [comment] 2018-03-25 02:56
@maheshambiga v1.3.1 is out and fixed some issues with error messages being emitted when we really shouldn't. https://github.com/benwiley4000/react-responsive-audio-player/releases/tag/v1.3.1

The issue you described doesn't seem like quite the same thing, but if you wouldn't mind, I would love to see if the issue persists with the new version.

**Comment by benwiley4000** [comment] 2018-03-26 22:26
I realized this may be a duplicate of #55, which I had reported earlier. Since this issue has received more discussion, I'll close the other one.

**Comment by benwiley4000** [comment] 2018-12-11 00:22
This issue hasn't come up for me lately so I'm going to close it. It may have been fixed either by a browser update or the refactors done for version 2.

If it comes back and we can get a repro, I'll re-open the issue. :slightly_smiling_face:

**Closed by benwiley4000** 2018-12-11 00:22 UTC
Labels: bug
